// <auto-generated />
using CâblageCeff.Utils;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CâblageCeff.Migrations
{
    [DbContext(typeof(DbModel))]
    [Migration("20250506114310_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.4");

            modelBuilder.Entity("CâblageCeff.Models.Panel", b =>
                {
                    b.Property<uint>("PanelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Batiment")
                        .HasColumnType("TEXT");

                    b.Property<string>("Emplacement")
                        .HasColumnType("TEXT");

                    b.Property<int?>("NbrPort")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("PanelId");

                    b.ToTable("Panels");
                });

            modelBuilder.Entity("CâblageCeff.Models.Patch", b =>
                {
                    b.Property<uint>("PatchId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Destination")
                        .HasColumnType("TEXT");

                    b.Property<string>("Emplacement")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<uint>("PanelId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Type")
                        .HasColumnType("TEXT");

                    b.HasKey("PatchId");

                    b.HasIndex("PanelId");

                    b.ToTable("Patchs");
                });

            modelBuilder.Entity("CâblageCeff.Models.Patch", b =>
                {
                    b.HasOne("CâblageCeff.Models.Panel", "Panel")
                        .WithMany("Patchs")
                        .HasForeignKey("PanelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Panel");
                });

            modelBuilder.Entity("CâblageCeff.Models.Panel", b =>
                {
                    b.Navigation("Patchs");
                });
#pragma warning restore 612, 618
        }
    }
}
